version: 2
jobs:
  build:
    docker:
      - image: andrewberry/sync-git-upstream:latest
    steps:
      - checkout
      - run: sync-git-upstream https://git.drupal.org/project/pathauto.git

workflows:
  version: 2
  build_workflow:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - patched
    jobs:
      - build
